Add a DualEncoder model that computes cosine similarity between two sets of documents
e2e-retrieval-in-continuous-space/e2e-retrieval pull request #4
Opened 2020-10-20 22:08 UTC by adamziel

Description

2020-10-21 16:14 UTC, ItsWayneYang commented on train_utils.py
> +    for i in range(batch_size):
I have found a way to rely entirely on Pytorch to compute this.  See `pairwise_cosine_similarity` in my latest PR.  Likely, Pytorch has vectorized implementation that will speed this up.

2020-10-21 16:14 UTC, ItsWayneYang commented on train_utils.py
> +class Encoder(nn.Module):
Instead of having a generic `Encoder` class and have some parts of model logic passed in the constructor, I feel that it is easier to encapsulate all model logic inside the subclass of nn.Module.  For example, we could have something like `BertAsFeatureExtractorEncoder(nn.Module)` which can encapsulate both this Encoder and BERTWrapper class.

The name, Encoder, might be too generic to tell what the model actually is since we will have have multiple models.

I would also suggest that model definitions go into their own files.

2020-10-21 16:14 UTC, ItsWayneYang commented on train_utils.py
> +        return self.linear.forward(embeddings)
It is recommended to do forward pass `self.linear(embeddings)`

https://discuss.pytorch.org/t/any-different-between-model-input-and-model-forward-input/3690/2

2020-10-22 19:24 UTC, adamziel commented on train_utils.py
> +class Encoder(nn.Module):
My intention was to only load BERT parameters into memory once and then reuse them in multiple models. But maybe one "training session" per script run will be just good enough. I'll bring everything into this class and iterate later if needed.

2020-10-23 06:01 UTC, ItsWayneYang commented on quora_dataset.py
> +            src_filename = cached_path("http://qim.fs.quoracdn.net/quora_duplicate_questions.tsv")
Cool

2020-10-23 07:17 UTC, ItsWayneYang requested changes

2020-10-23 07:17 UTC, ItsWayneYang commented on quora_dataset.py
> +                if limit is not None and i >= limit:
This returns (limit + 1) Examples.

2020-10-23 07:17 UTC, ItsWayneYang commented on train_utils.py
> +        yield list(zip(*data[i: i + batch_size]))
Thanks for fixing this!

2020-10-23 07:17 UTC, ItsWayneYang commented on models.py
> +            self.cached_embeddings[key] = Variable(embeddings)
I think we don't need to wrap embeddings with `Variable` :

https://www.quora.com/What-is-the-difference-between-a-Tensor-and-a-Variable-in-Pytorch

Also even if embeddings is a Tensor already, does it need required_grad=true?

2020-10-24 06:52 UTC, merged